# Generated by Django 2.1.1 on 2018-10-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='pic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
