# Generated by Django 2.1.1 on 2018-10-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181006_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
