# Generated by Django 2.1.1 on 2018-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181006_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='addtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
