# Generated by Django 2.1.1 on 2018-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_shops_addtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='addtime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
