# Generated by Django 2.1.1 on 2018-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181006_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
