# Generated by Django 2.1.1 on 2018-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181006_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='pic',
            field=models.CharField(max_length=255, null=True, verbose_name='形象图'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.IntegerField(null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='库存'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='text',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
    ]
