# Generated by Django 2.1.1 on 2018-10-07 05:57

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181006_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, default='test', null=True, verbose_name='描述    '),
        ),
    ]
