# Generated by Django 2.1.1 on 2018-10-07 06:07

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181007_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='内容\t'),
        ),
    ]
