# Generated by Django 2.1.1 on 2018-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181007_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='姓名')),
                ('headerimg', models.ImageField(null=True, upload_to='', verbose_name='头像')),
            ],
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': '商品列表', 'verbose_name_plural': '商品列表'},
        ),
    ]
