# Generated by Django 2.1.1 on 2018-10-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181007_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_users',
            name='addtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='shop_users',
            name='headerimg',
            field=models.ImageField(null=True, upload_to='img', verbose_name='头像'),
        ),
    ]
