# Generated by Django 2.1.1 on 2018-10-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20181007_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop_users',
            options={'verbose_name': '商城用户', 'verbose_name_plural': '商城用户'},
        ),
    ]
