# Generated by Django 2.1.1 on 2018-10-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181007_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_users',
            name='adress',
            field=models.CharField(max_length=255, null=True, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='shop_users',
            name='score',
            field=models.IntegerField(default=50, verbose_name='用户积分'),
        ),
    ]
