# Generated by Django 2.1.1 on 2018-10-09 05:50

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181007_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='抢购结束时间'),
        ),
        migrations.AddField(
            model_name='shops',
            name='oldprice',
            field=models.FloatField(null=True, verbose_name='原价'),
        ),
        migrations.AddField(
            model_name='shops',
            name='sales',
            field=models.IntegerField(null=True, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='shops',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='抢购开始时间'),
        ),
        migrations.AlterField(
            model_name='shop_users',
            name='headerimg',
            field=models.ImageField(null=True, upload_to='img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='pic',
            field=models.ImageField(null=True, upload_to='img', verbose_name='形象图'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.FloatField(null=True, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='详情'),
        ),
    ]
