# Generated by Django 2.1.1 on 2018-10-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181009_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='价格'),
        ),
    ]
