# Generated by Django 2.1.1 on 2018-10-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181009_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_users',
            name='password',
            field=models.CharField(max_length=255, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='shop_users',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='用户名'),
        ),
    ]
