# Generated by Django 2.1.1 on 2018-10-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_shop_users_headerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_users',
            name='password',
            field=models.CharField(editable=False, max_length=255, null=True, verbose_name='密码'),
        ),
    ]
