# Generated by Django 2.1.1 on 2018-10-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181011_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=50, verbose_name='订单id')),
                ('shopid', models.IntegerField(editable=False, verbose_name='商品id')),
                ('uid', models.IntegerField(editable=False, verbose_name='用户id')),
                ('shopname', models.CharField(max_length=255, null=True, verbose_name='商品名称')),
                ('uname', models.CharField(max_length=255, null=True, verbose_name='用户名')),
                ('adress', models.CharField(max_length=255, null=True, verbose_name='收货地址')),
                ('state', models.CharField(max_length=255, null=True, verbose_name='订单状态')),
                ('addtime', models.DateTimeField(verbose_name='订单生成时间')),
                ('paytime', models.DateTimeField(null=True, verbose_name='订单支付时间')),
                ('paymoney', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='支付价格')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
            },
        ),
    ]
