# Generated by Django 2.1.1 on 2018-10-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20181011_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_users',
            name='score',
            field=models.FloatField(default=5000, verbose_name='用户积分'),
        ),
    ]
