# Generated by Django 2.1.1 on 2018-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20181011_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_users',
            name='phone',
            field=models.CharField(max_length=255, null=True, verbose_name='联系电话'),
        ),
    ]
